/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alfnave.visualizacao;

import javax.swing.JOptionPane;

/**
 *
 * @author pc-asus
 */
public class Posicao6 extends javax.swing.JFrame {

    /**
     * Creates new form Posicao6
     */
    public Posicao6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        posicao6 = new javax.swing.JLabel();
        botaoesquerda7 = new javax.swing.JButton();
        botaodireita = new javax.swing.JButton();
        botaobaixo = new javax.swing.JButton();
        botaoacima = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Naverick");

        posicao6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/posicoes/posicao6.png"))); // NOI18N

        botaoesquerda7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/setas/setaesquerda.png"))); // NOI18N
        botaoesquerda7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoesquerda7ActionPerformed(evt);
            }
        });

        botaodireita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/setas/setadireita.png"))); // NOI18N
        botaodireita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaodireitaActionPerformed(evt);
            }
        });

        botaobaixo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/setas/setabaixo.png"))); // NOI18N
        botaobaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaobaixoActionPerformed(evt);
            }
        });

        botaoacima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/setas/setacima.png"))); // NOI18N
        botaoacima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoacimaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(posicao6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoesquerda7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoacima, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaodireita, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaobaixo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botaoacima, botaobaixo, botaodireita, botaoesquerda7});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaodireita, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoacima, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoesquerda7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaobaixo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(posicao6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botaoacima, botaobaixo, botaodireita, botaoesquerda7});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoesquerda7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoesquerda7ActionPerformed
        Posicao5 posicao5 = new Posicao5();
        posicao5.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoesquerda7ActionPerformed

    private void botaodireitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaodireitaActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Sem chances,a nave ira colidir!");
    }//GEN-LAST:event_botaodireitaActionPerformed

    private void botaobaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaobaixoActionPerformed
       JOptionPane.showMessageDialog(rootPane, "Comando invalido!");
    }//GEN-LAST:event_botaobaixoActionPerformed

    private void botaoacimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoacimaActionPerformed
       Posicao8 posicao8 = new Posicao8();
       posicao8.setVisible(true);
       dispose();
    }//GEN-LAST:event_botaoacimaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Posicao6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Posicao6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Posicao6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Posicao6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Posicao6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoacima;
    private javax.swing.JButton botaobaixo;
    private javax.swing.JButton botaodireita;
    private javax.swing.JButton botaoesquerda7;
    private javax.swing.JLabel posicao6;
    // End of variables declaration//GEN-END:variables
}
