/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alfnave.visualizacao;

import javax.swing.JOptionPane;

/**
 *
 * @author pc-asus
 */
public class Posicao9 extends javax.swing.JFrame {

    /**
     * Creates new form Posicao9
     */
    public Posicao9() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        posicao9 = new javax.swing.JLabel();
        botaodireita = new javax.swing.JButton();
        botaobaixo = new javax.swing.JButton();
        botaoacima = new javax.swing.JButton();
        botaoesquerda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Naverick");

        posicao9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/posicoes/posicao9.png"))); // NOI18N

        botaodireita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/setas/setadireita.png"))); // NOI18N
        botaodireita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaodireitaActionPerformed(evt);
            }
        });

        botaobaixo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/setas/setabaixo.png"))); // NOI18N
        botaobaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaobaixoActionPerformed(evt);
            }
        });

        botaoacima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/setas/setacima.png"))); // NOI18N
        botaoacima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoacimaActionPerformed(evt);
            }
        });

        botaoesquerda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/setas/setaesquerda.png"))); // NOI18N
        botaoesquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoesquerdaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(posicao9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoesquerda, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoacima, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaodireita, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaobaixo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botaoacima, botaobaixo, botaodireita, botaoesquerda});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(posicao9, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaodireita, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoacima, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoesquerda, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaobaixo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botaoacima, botaobaixo, botaodireita, botaoesquerda});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoesquerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoesquerdaActionPerformed
         JOptionPane.showMessageDialog(rootPane, "Sem chances,a nave ira colidir!");
    }//GEN-LAST:event_botaoesquerdaActionPerformed

    private void botaobaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaobaixoActionPerformed
        Posicao7 posicao7 = new Posicao7();
        posicao7.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaobaixoActionPerformed

    private void botaodireitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaodireitaActionPerformed
       JOptionPane.showMessageDialog(rootPane, "Sem chances,a nave ira colidir!");
    }//GEN-LAST:event_botaodireitaActionPerformed

    private void botaoacimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoacimaActionPerformed
        Posicao12 posicao12 = new Posicao12();
        posicao12.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoacimaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Posicao9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Posicao9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Posicao9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Posicao9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Posicao9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoacima;
    private javax.swing.JButton botaobaixo;
    private javax.swing.JButton botaodireita;
    private javax.swing.JButton botaoesquerda;
    private javax.swing.JLabel posicao9;
    // End of variables declaration//GEN-END:variables
}
